/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux localhost.localdomain 2.6.23.17-88.fc7 #1 SMP Thu May 15 00:35:10 EDT 2008 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "四  5月 13 20:13:40 CST 2010"
#define BUILD_ENV_SRCDIR "."
#define BUILD_ENV_BUILDDIR "."
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "localhost.localdomain"
#define BUILD_ENV_COMPILER "/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
