/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#include "mdm_types.h"
#include "rcl.h"
#include "stl.h"

const MdmHandlerFuncInfo oidHandlerFuncsTable[]= { 
  /*   0 */ {NULL, NULL},
  /*   1 */ {rcl_igdObject, stl_igdObject},
  /*   2 */ {rcl_igdDeviceInfoObject, stl_igdDeviceInfoObject},
  /*   3 */ {rcl_vendorConfigFileObject, stl_vendorConfigFileObject},
  /*   4 */ {rcl_syslogCfgObject, stl_syslogCfgObject},
  /*   5 */ {rcl_loginCfgObject, stl_loginCfgObject},
  /*   6 */ {rcl_appCfgObject, stl_appCfgObject},
  /*   7 */ {rcl_httpdCfgObject, stl_httpdCfgObject},
  /*   8 */ {rcl_tr69cCfgObject, stl_tr69cCfgObject},
#if defined(DMP_X_BROADCOM_COM_TR64_1)
  /*   9 */ {rcl_tr64cCfgObject, stl_tr64cCfgObject},
#else
  /*   9 */ {NULL, NULL},
#endif
  /*  10 */ {rcl_sshdCfgObject, stl_sshdCfgObject},
  /*  11 */ {rcl_telnetdCfgObject, stl_telnetdCfgObject},
  /*  12 */ {rcl_consoledCfgObject, stl_consoledCfgObject},
  /*  13 */ {rcl_smdCfgObject, stl_smdCfgObject},
  /*  14 */ {rcl_sskCfgObject, stl_sskCfgObject},
  /*  15 */ {rcl_snmpdCfgObject, stl_snmpdCfgObject},
  /*  16 */ {rcl_ftpdCfgObject, stl_ftpdCfgObject},
  /*  17 */ {rcl_tftpdCfgObject, stl_tftpdCfgObject},
  /*  18 */ {rcl_pppdCfgObject, stl_pppdCfgObject},
  /*  19 */ {rcl_icmpCfgObject, stl_icmpCfgObject},
#if defined(DMP_X_BROADCOM_COM_UPNP_1)
  /*  20 */ {rcl_upnpCfgObject, stl_upnpCfgObject},
#else
  /*  20 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DNSPROXY_1)
  /*  21 */ {rcl_dnsProxyCfgObject, stl_dnsProxyCfgObject},
#else
  /*  21 */ {NULL, NULL},
#endif
  /*  22 */ {rcl_ethernetSwitchObject, stl_ethernetSwitchObject},
#if defined(DMP_X_BROADCOM_COM_PWRMNGT_1)
  /*  23 */ {rcl_pwrMngtObject, stl_pwrMngtObject},
#else
  /*  23 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_STANDBY_1)
  /*  24 */ {rcl_standbyCfgObject, stl_standbyCfgObject},
#else
  /*  24 */ {NULL, NULL},
#endif
  /*  25 */ {rcl_deviceConfigObject, stl_deviceConfigObject},
  /*  26 */ {rcl_managementServerObject, stl_managementServerObject},
#if defined(DMP_DEVICEASSOCIATION_1)
  /*  27 */ {rcl_manageableDeviceObject, stl_manageableDeviceObject},
#else
  /*  27 */ {NULL, NULL},
#endif
#if defined(DMP_TIME_1)
  /*  28 */ {rcl_timeServerCfgObject, stl_timeServerCfgObject},
#else
  /*  28 */ {NULL, NULL},
#endif
#if defined(DMP_BRIDGING_1)
  /*  29 */ {rcl_l2BridgingObject, stl_l2BridgingObject},
#else
  /*  29 */ {NULL, NULL},
#endif
#if defined(DMP_BRIDGING_1) && defined(DMP_BRIDGING_1)
  /*  30 */ {rcl_l2BridgingEntryObject, stl_l2BridgingEntryObject},
#else
  /*  30 */ {NULL, NULL},
#endif
#if defined(DMP_BRIDGING_1) && defined(DMP_BRIDGING_1)
  /*  31 */ {rcl_l2BridgingFilterObject, stl_l2BridgingFilterObject},
#else
  /*  31 */ {NULL, NULL},
#endif
#if defined(DMP_BRIDGING_1) && defined(DMP_BRIDGING_1)
  /*  32 */ {rcl_l2BridgingIntfObject, stl_l2BridgingIntfObject},
#else
  /*  32 */ {NULL, NULL},
#endif
#if defined(DMP_QOS_1)
  /*  33 */ {rcl_qMgmtObject, stl_qMgmtObject},
#else
  /*  33 */ {NULL, NULL},
#endif
#if defined(DMP_QOS_1) && defined(DMP_QOS_1)
  /*  34 */ {rcl_qMgmtClassificationObject, stl_qMgmtClassificationObject},
#else
  /*  34 */ {NULL, NULL},
#endif
#if defined(DMP_QOS_1) && defined(DMP_QOS_1)
  /*  35 */ {rcl_qMgmtQueueObject, stl_qMgmtQueueObject},
#else
  /*  35 */ {NULL, NULL},
#endif
#if defined(DMP_IPPING_1)
  /*  36 */ {rcl_ipPingDiagObject, stl_ipPingDiagObject},
#else
  /*  36 */ {NULL, NULL},
#endif
  /*  37 */ {rcl_lanDevObject, stl_lanDevObject},
  /*  38 */ {rcl_igmpSnoopingCfgObject, stl_igmpSnoopingCfgObject},
  /*  39 */ {rcl_lanHostCfgObject, stl_lanHostCfgObject},
  /*  40 */ {rcl_lanIpIntfObject, stl_lanIpIntfObject},
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /*  41 */ {rcl_lanIpIntfFirewallExceptionObject, stl_lanIpIntfFirewallExceptionObject},
#else
  /*  41 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /*  42 */ {rcl_ipFilterCfgObject, stl_ipFilterCfgObject},
#else
  /*  42 */ {NULL, NULL},
#endif
  /*  43 */ {rcl_dHCPConditionalServingObject, stl_dHCPConditionalServingObject},
#if defined(DMP_X_BROADCOM_COM_IPV6_1)
  /*  44 */ {rcl_ipv6LanHostCfgObject, stl_ipv6LanHostCfgObject},
#else
  /*  44 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_IPV6_1)
  /*  45 */ {rcl_mldSnoopingCfgObject, stl_mldSnoopingCfgObject},
#else
  /*  45 */ {NULL, NULL},
#endif
#if defined(DMP_ETHERNETLAN_1)
  /*  46 */ {rcl_lanEthIntfObject, stl_lanEthIntfObject},
#else
  /*  46 */ {NULL, NULL},
#endif
#if defined(DMP_ETHERNETLAN_1) && defined(DMP_ETHERNETLAN_1)
  /*  47 */ {rcl_lanEthIntfStatsObject, stl_lanEthIntfStatsObject},
#else
  /*  47 */ {NULL, NULL},
#endif
#if defined(DMP_USBLAN_1)
  /*  48 */ {rcl_lanUsbIntfObject, stl_lanUsbIntfObject},
#else
  /*  48 */ {NULL, NULL},
#endif
#if defined(DMP_USBLAN_1) && defined(DMP_USBLAN_1)
  /*  49 */ {rcl_lanUsbIntfStatsObject, stl_lanUsbIntfStatsObject},
#else
  /*  49 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1)
  /*  50 */ {rcl_lanWlanObject, stl_lanWlanObject},
#else
  /*  50 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_WIFILAN_1)
  /*  51 */ {rcl_lanWlanAssociatedDeviceEntryObject, stl_lanWlanAssociatedDeviceEntryObject},
#else
  /*  51 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_WIFILAN_1)
  /*  52 */ {rcl_lanWlanWepKeyObject, stl_lanWlanWepKeyObject},
#else
  /*  52 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_WIFILAN_1)
  /*  53 */ {rcl_lanWlanPreSharedKeyObject, stl_lanWlanPreSharedKeyObject},
#else
  /*  53 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  54 */ {rcl_wlanAdapterObject, stl_wlanAdapterObject},
#else
  /*  54 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  55 */ {rcl_wlBaseCfgObject, stl_wlBaseCfgObject},
#else
  /*  55 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  56 */ {rcl_wlStaticWdsCfgObject, stl_wlStaticWdsCfgObject},
#else
  /*  56 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  57 */ {rcl_wlWdsCfgObject, stl_wlWdsCfgObject},
#else
  /*  57 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  58 */ {rcl_wlScanWdsCfgObject, stl_wlScanWdsCfgObject},
#else
  /*  58 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  59 */ {rcl_wlMimoCfgObject, stl_wlMimoCfgObject},
#else
  /*  59 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  60 */ {rcl_wlSesCfgObject, stl_wlSesCfgObject},
#else
  /*  60 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  61 */ {rcl_wlVirtIntfCfgObject, stl_wlVirtIntfCfgObject},
#else
  /*  61 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  62 */ {rcl_wlMacFltObject, stl_wlMacFltObject},
#else
  /*  62 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  63 */ {rcl_wlKey64CfgObject, stl_wlKey64CfgObject},
#else
  /*  63 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  64 */ {rcl_wlKey128CfgObject, stl_wlKey128CfgObject},
#else
  /*  64 */ {NULL, NULL},
#endif
#if defined(DMP_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1) && defined(DMP_X_BROADCOM_COM_WIFILAN_1)
  /*  65 */ {rcl_wlWpsCfgObject, stl_wlWpsCfgObject},
#else
  /*  65 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCALAN_1)
  /*  66 */ {rcl_lanMocaIntfObject, stl_lanMocaIntfObject},
#else
  /*  66 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCALAN_1) && defined(DMP_X_BROADCOM_COM_MOCALAN_1)
  /*  67 */ {rcl_lanMocaIntfStatusObject, stl_lanMocaIntfStatusObject},
#else
  /*  67 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCALAN_1) && defined(DMP_X_BROADCOM_COM_MOCALAN_1)
  /*  68 */ {rcl_lanMocaIntfStatsObject, stl_lanMocaIntfStatsObject},
#else
  /*  68 */ {NULL, NULL},
#endif
  /*  69 */ {rcl_lanHostsObject, stl_lanHostsObject},
  /*  70 */ {rcl_lanHostEntryObject, stl_lanHostEntryObject},
  /*  71 */ {rcl_multiWanObject, stl_multiWanObject},
  /*  72 */ {rcl_mWANPortObject, stl_mWANPortObject},
#if defined(DMP_X_VENDOR_COM_FAILOVER_1)
  /*  73 */ {rcl_failoverCfgObject, stl_failoverCfgObject},
#else
  /*  73 */ {NULL, NULL},
#endif
  /*  74 */ {rcl_wanDevObject, stl_wanDevObject},
  /*  75 */ {rcl_wanCommonIntfCfgObject, stl_wanCommonIntfCfgObject},
#if defined(DMP_X_BROADCOM_COM_XTMSTATS_1)
  /*  76 */ {rcl_xtmInterfaceStatsObject, stl_xtmInterfaceStatsObject},
#else
  /*  76 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1)
  /*  77 */ {rcl_wanDslIntfCfgObject, stl_wanDslIntfCfgObject},
#else
  /*  77 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_X_BROADCOM_COM_ADSLWAN_1)
  /*  78 */ {rcl_wanBertTestObject, stl_wanBertTestObject},
#else
  /*  78 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1)
  /*  79 */ {rcl_wanDslIntfStatsObject, stl_wanDslIntfStatsObject},
#else
  /*  79 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1)
  /*  80 */ {rcl_wanDslIntfStatsTotalObject, stl_wanDslIntfStatsTotalObject},
#else
  /*  80 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1)
  /*  81 */ {rcl_wanDslIntfStatsShowtimeObject, stl_wanDslIntfStatsShowtimeObject},
#else
  /*  81 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1)
  /*  82 */ {rcl_wanDslIntfStatsCurrentDayObject, stl_wanDslIntfStatsCurrentDayObject},
#else
  /*  82 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_ADSLWAN_1)
  /*  83 */ {rcl_wanDslIntfStatsQuarterHourObject, stl_wanDslIntfStatsQuarterHourObject},
#else
  /*  83 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_VDSL2WAN_1)
  /*  84 */ {rcl_wanDslTestParamsObject, stl_wanDslTestParamsObject},
#else
  /*  84 */ {NULL, NULL},
#endif
#if defined(DMP_ETHERNETWAN_1)
  /*  85 */ {rcl_wanEthIntfObject, stl_wanEthIntfObject},
#else
  /*  85 */ {NULL, NULL},
#endif
#if defined(DMP_ETHERNETWAN_1) && defined(DMP_ETHERNETWAN_1)
  /*  86 */ {rcl_wanEthIntfStatsObject, stl_wanEthIntfStatsObject},
#else
  /*  86 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCAWAN_1)
  /*  87 */ {rcl_wanMocaIntfObject, stl_wanMocaIntfObject},
#else
  /*  87 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCAWAN_1) && defined(DMP_X_BROADCOM_COM_MOCAWAN_1)
  /*  88 */ {rcl_wanMocaIntfStatusObject, stl_wanMocaIntfStatusObject},
#else
  /*  88 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MOCAWAN_1) && defined(DMP_X_BROADCOM_COM_MOCAWAN_1)
  /*  89 */ {rcl_wanMocaIntfStatsObject, stl_wanMocaIntfStatsObject},
#else
  /*  89 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_L2TPAC_1)
  /*  90 */ {rcl_l2tpAcIntfConfigObject, stl_l2tpAcIntfConfigObject},
#else
  /*  90 */ {NULL, NULL},
#endif
#if defined(DMP_DSLDIAGNOSTICS_1)
  /*  91 */ {rcl_wanDslDiagObject, stl_wanDslDiagObject},
#else
  /*  91 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DIAG_1)
  /*  92 */ {rcl_wanDslProprietaryDiagObject, stl_wanDslProprietaryDiagObject},
#else
  /*  92 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DIAG_1) && defined(DMP_X_BROADCOM_COM_DIAG_1)
  /*  93 */ {rcl_wanDslDiagPlnObject, stl_wanDslDiagPlnObject},
#else
  /*  93 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DIAG_1) && defined(DMP_X_BROADCOM_COM_DIAG_1)
  /*  94 */ {rcl_wanDslDiagNonLinearityObject, stl_wanDslDiagNonLinearityObject},
#else
  /*  94 */ {NULL, NULL},
#endif
  /*  95 */ {rcl_wanConnDeviceObject, stl_wanConnDeviceObject},
#if defined(DMP_X_BROADCOM_COM_ATMLOOPBACK_1)
  /*  96 */ {rcl_wanAtmF4EndToEndLoopbackDiagObject, stl_wanAtmF4EndToEndLoopbackDiagObject},
#else
  /*  96 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_ATMLOOPBACK_1)
  /*  97 */ {rcl_wanAtmF4LoopbackDiagObject, stl_wanAtmF4LoopbackDiagObject},
#else
  /*  97 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_ATMLOOPBACK_1)
  /*  98 */ {rcl_wanAtmF5EndToEndLoopbackDiagObject, stl_wanAtmF5EndToEndLoopbackDiagObject},
#else
  /*  98 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1)
  /*  99 */ {rcl_wanDslLinkCfgObject, stl_wanDslLinkCfgObject},
#else
  /*  99 */ {NULL, NULL},
#endif
#if defined(DMP_ADSLWAN_1) && defined(DMP_X_BROADCOM_COM_ADSLWAN_1)
  /* 100 */ {rcl_wanDslAtmParamsObject, stl_wanDslAtmParamsObject},
#else
  /* 100 */ {NULL, NULL},
#endif
#if defined(DMP_ATMLOOPBACK_1)
  /* 101 */ {rcl_wanAtm5LoopbackDiagObject, stl_wanAtm5LoopbackDiagObject},
#else
  /* 101 */ {NULL, NULL},
#endif
#if defined(DMP_PTMWAN_1)
  /* 102 */ {rcl_wanPtmLinkCfgObject, stl_wanPtmLinkCfgObject},
#else
  /* 102 */ {NULL, NULL},
#endif
#if defined(DMP_ETHERNETWAN_1)
  /* 103 */ {rcl_wanEthLinkCfgObject, stl_wanEthLinkCfgObject},
#else
  /* 103 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_L2TPAC_1)
  /* 104 */ {rcl_l2tpAcLinkConfigObject, stl_l2tpAcLinkConfigObject},
#else
  /* 104 */ {NULL, NULL},
#endif
  /* 105 */ {rcl_wanIpConnObject, stl_wanIpConnObject},
  /* 106 */ {rcl_wanIpConnPortmappingObject, stl_wanIpConnPortmappingObject},
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 107 */ {rcl_wanIpConnPortTriggeringObject, stl_wanIpConnPortTriggeringObject},
#else
  /* 107 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 108 */ {rcl_wanIpConnFirewallExceptionObject, stl_wanIpConnFirewallExceptionObject},
#else
  /* 108 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 109 */ {rcl_macFilterObject, stl_macFilterObject},
#else
  /* 109 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1) && defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 110 */ {rcl_macFilterCfgObject, stl_macFilterCfgObject},
#else
  /* 110 */ {NULL, NULL},
#endif
  /* 111 */ {rcl_wanIpConnStatsObject, stl_wanIpConnStatsObject},
  /* 112 */ {rcl_wanPppConnObject, stl_wanPppConnObject},
  /* 113 */ {rcl_wanPppConnPortmappingObject, stl_wanPppConnPortmappingObject},
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 114 */ {rcl_wanPppConnPortTriggeringObject, stl_wanPppConnPortTriggeringObject},
#else
  /* 114 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 115 */ {rcl_wanPppConnFirewallExceptionObject, stl_wanPppConnFirewallExceptionObject},
#else
  /* 115 */ {NULL, NULL},
#endif
  /* 116 */ {rcl_wanPppConnStatsObject, stl_wanPppConnStatsObject},
  /* 117 */ {rcl_l3ForwardingObject, stl_l3ForwardingObject},
  /* 118 */ {rcl_l3ForwardingEntryObject, stl_l3ForwardingEntryObject},
#if defined(DMP_X_BROADCOM_COM_IPV6_1)
  /* 119 */ {rcl_ipv6L3ForwardingObject, stl_ipv6L3ForwardingObject},
#else
  /* 119 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_IPV6_1) && defined(DMP_X_BROADCOM_COM_IPV6_1)
  /* 120 */ {rcl_ipv6L3ForwardingEntryObject, stl_ipv6L3ForwardingEntryObject},
#else
  /* 120 */ {NULL, NULL},
#endif
  /* 121 */ {rcl_servicesObject, stl_servicesObject},
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 122 */ {rcl_remoteAccessObject, stl_remoteAccessObject},
#else
  /* 122 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1)
  /* 123 */ {rcl_storageServiceObject, stl_storageServiceObject},
#else
  /* 123 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 124 */ {rcl_userAccountObject, stl_userAccountObject},
#else
  /* 124 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 125 */ {rcl_capabilitesObject, stl_capabilitesObject},
#else
  /* 125 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 126 */ {rcl_networkInfoObject, stl_networkInfoObject},
#else
  /* 126 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 127 */ {rcl_networkServerObject, stl_networkServerObject},
#else
  /* 127 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 128 */ {rcl_physicalMediumObject, stl_physicalMediumObject},
#else
  /* 128 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 129 */ {rcl_logicalVolumeObject, stl_logicalVolumeObject},
#else
  /* 129 */ {NULL, NULL},
#endif
#if defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1) && defined(DMP_STORAGESERVICE_1)
  /* 130 */ {rcl_folderObject, stl_folderObject},
#else
  /* 130 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1)
  /* 131 */ {rcl_voiceObject, stl_voiceObject},
#else
  /* 131 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 132 */ {rcl_voiceCapObject, stl_voiceCapObject},
#else
  /* 132 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_SIPENDPOINT_1)
  /* 133 */ {rcl_voiceCapSipObject, stl_voiceCapSipObject},
#else
  /* 133 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_MGCPENDPOINT_1)
  /* 134 */ {rcl_voiceCapMgcpObject, stl_voiceCapMgcpObject},
#else
  /* 134 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 135 */ {rcl_voiceCapCodecsObject, stl_voiceCapCodecsObject},
#else
  /* 135 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 136 */ {rcl_voiceProfObject, stl_voiceProfObject},
#else
  /* 136 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 137 */ {rcl_voiceProfProviderObject, stl_voiceProfProviderObject},
#else
  /* 137 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_SIPENDPOINT_1)
  /* 138 */ {rcl_voiceProfSipObject, stl_voiceProfSipObject},
#else
  /* 138 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_SIPENDPOINT_1)
  /* 139 */ {rcl_voiceProfSipSubscribeObject, stl_voiceProfSipSubscribeObject},
#else
  /* 139 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_MGCPENDPOINT_1)
  /* 140 */ {rcl_voiceProfMgcpObject, stl_voiceProfMgcpObject},
#else
  /* 140 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 141 */ {rcl_voiceProfRtpObject, stl_voiceProfRtpObject},
#else
  /* 141 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 142 */ {rcl_voiceProfRtpSrtpObject, stl_voiceProfRtpSrtpObject},
#else
  /* 142 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 143 */ {rcl_voiceProfFaxT38Object, stl_voiceProfFaxT38Object},
#else
  /* 143 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 144 */ {rcl_voiceLineObject, stl_voiceLineObject},
#else
  /* 144 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_SIPENDPOINT_1)
  /* 145 */ {rcl_voiceLineSipObject, stl_voiceLineSipObject},
#else
  /* 145 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 146 */ {rcl_voiceLineCallingFeaturesObject, stl_voiceLineCallingFeaturesObject},
#else
  /* 146 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 147 */ {rcl_voiceLineProcessingObject, stl_voiceLineProcessingObject},
#else
  /* 147 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 148 */ {rcl_voiceLineCodecObject, stl_voiceLineCodecObject},
#else
  /* 148 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 149 */ {rcl_voiceLineCodecListObject, stl_voiceLineCodecListObject},
#else
  /* 149 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1) && defined(DMP_ENDPOINT_1)
  /* 150 */ {rcl_voiceLineStatsObject, stl_voiceLineStatsObject},
#else
  /* 150 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_TAENDPOINT_1)
  /* 151 */ {rcl_voicePhyIntfObject, stl_voicePhyIntfObject},
#else
  /* 151 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_TAENDPOINT_1)
  /* 152 */ {rcl_voicePhyIntfTestsObject, stl_voicePhyIntfTestsObject},
#else
  /* 152 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_X_BROADCOM_COM_PSTNENDPOINT_1)
  /* 153 */ {rcl_voicePstnObject, stl_voicePstnObject},
#else
  /* 153 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_X_BROADCOM_COM_NTR_1)
  /* 154 */ {rcl_voiceNtrObject, stl_voiceNtrObject},
#else
  /* 154 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_X_BROADCOM_COM_NTR_1) && defined(DMP_X_BROADCOM_COM_NTR_1)
  /* 155 */ {rcl_voiceNtrHistoryObject, stl_voiceNtrHistoryObject},
#else
  /* 155 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_X_BROADCOM_COM_DECTENDPOINT_1)
  /* 156 */ {rcl_voiceDECTIntfObject, stl_voiceDECTIntfObject},
#else
  /* 156 */ {NULL, NULL},
#endif
#if defined(DMP_ENDPOINT_1) && defined(DMP_X_BROADCOM_COM_DECTENDPOINT_1) && defined(DMP_X_BROADCOM_COM_DECTENDPOINT_1)
  /* 157 */ {rcl_voiceDECTHandsetObject, stl_voiceDECTHandsetObject},
#else
  /* 157 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SNMP_1)
  /* 158 */ {rcl_snmpCfgObject, stl_snmpCfgObject},
#else
  /* 158 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_SECURITY_1)
  /* 159 */ {rcl_secDmzHostCfgObject, stl_secDmzHostCfgObject},
#else
  /* 159 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1)
  /* 160 */ {rcl_macFilterPolicyObject, stl_macFilterPolicyObject},
#else
  /* 160 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_ACCESSTIMERESTRICTION_1)
  /* 161 */ {rcl_accessTimeRestrictionObject, stl_accessTimeRestrictionObject},
#else
  /* 161 */ {NULL, NULL},
#endif
  /* 162 */ {rcl_timeScheduleObject, stl_timeScheduleObject},
  /* 163 */ {rcl_urlFilterCfgObject, stl_urlFilterCfgObject},
  /* 164 */ {rcl_urlFilterListObject, stl_urlFilterListObject},
#if defined(DMP_X_BROADCOM_COM_DYNAMICDNS_1)
  /* 165 */ {rcl_dDnsCfgObject, stl_dDnsCfgObject},
#else
  /* 165 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_IPPRINTING_1)
  /* 166 */ {rcl_ippCfgObject, stl_ippCfgObject},
#else
  /* 166 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DLNA_1)
  /* 167 */ {rcl_dlnaObject, stl_dlnaObject},
#else
  /* 167 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DLNA_1) && defined(DMP_X_BROADCOM_COM_DLNA_1)
  /* 168 */ {rcl_dmsCfgObject, stl_dmsCfgObject},
#else
  /* 168 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DEBUG_1)
  /* 169 */ {rcl_wanDebugPortMirroringCfgObject, stl_wanDebugPortMirroringCfgObject},
#else
  /* 169 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_IPSEC_1)
  /* 170 */ {rcl_ipSecCfgObject, stl_ipSecCfgObject},
#else
  /* 170 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_DIGITALCERTIFICATES_1)
  /* 171 */ {rcl_certificateCfgObject, stl_certificateCfgObject},
#else
  /* 171 */ {NULL, NULL},
#endif
  /* 172 */ {rcl_wapiCertificateObject, stl_wapiCertificateObject},
  /* 173 */ {rcl_wapiAsCertificateObject, stl_wapiAsCertificateObject},
  /* 174 */ {rcl_wapiIssuedCertificateObject, stl_wapiIssuedCertificateObject},
  /* 175 */ {rcl_networkConfigObject, stl_networkConfigObject},
  /* 176 */ {rcl_interfaceControlObject, stl_interfaceControlObject},
#if defined(DMP_X_BROADCOM_COM_P8021AG_1)
  /* 177 */ {rcl_p8021agCfgObject, stl_p8021agCfgObject},
#else
  /* 177 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_IGMP_1)
  /* 178 */ {rcl_igmpCfgObject, stl_igmpCfgObject},
#else
  /* 178 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_MLD_1)
  /* 179 */ {rcl_mldCfgObject, stl_mldCfgObject},
#else
  /* 179 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1)
  /* 180 */ {rcl_ituTOrgObject, stl_ituTOrgObject},
#else
  /* 180 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 181 */ {rcl_g_984_4Object, stl_g_984_4Object},
#else
  /* 181 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 182 */ {rcl_equipmentManagementObject, stl_equipmentManagementObject},
#else
  /* 182 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 183 */ {rcl_ontGObject, stl_ontGObject},
#else
  /* 183 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 184 */ {rcl_ont2GObject, stl_ont2GObject},
#else
  /* 184 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 185 */ {rcl_ontDataObject, stl_ontDataObject},
#else
  /* 185 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 186 */ {rcl_softwareImageObject, stl_softwareImageObject},
#else
  /* 186 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 187 */ {rcl_cardHolderObject, stl_cardHolderObject},
#else
  /* 187 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 188 */ {rcl_circuitPackObject, stl_circuitPackObject},
#else
  /* 188 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 189 */ {rcl_powerSheddingObject, stl_powerSheddingObject},
#else
  /* 189 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 190 */ {rcl_portMappingPackageGObject, stl_portMappingPackageGObject},
#else
  /* 190 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 191 */ {rcl_aniManagementObject, stl_aniManagementObject},
#else
  /* 191 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 192 */ {rcl_aniGObject, stl_aniGObject},
#else
  /* 192 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 193 */ {rcl_tContObject, stl_tContObject},
#else
  /* 193 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 194 */ {rcl_gemPortNetworkCtpObject, stl_gemPortNetworkCtpObject},
#else
  /* 194 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 195 */ {rcl_bCM_GemPortNetworkCtpObject, stl_bCM_GemPortNetworkCtpObject},
#else
  /* 195 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 196 */ {rcl_gemInterworkingTpObject, stl_gemInterworkingTpObject},
#else
  /* 196 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 197 */ {rcl_multicastGemInterworkingTpObject, stl_multicastGemInterworkingTpObject},
#else
  /* 197 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 198 */ {rcl_gemInterworkingTpMulticastAddressTableObject, stl_gemInterworkingTpMulticastAddressTableObject},
#else
  /* 198 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 199 */ {rcl_gemPortPmHistoryDataObject, stl_gemPortPmHistoryDataObject},
#else
  /* 199 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 200 */ {rcl_galEthernetProfileObject, stl_galEthernetProfileObject},
#else
  /* 200 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 201 */ {rcl_galEthernetPmHistoryDataObject, stl_galEthernetPmHistoryDataObject},
#else
  /* 201 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 202 */ {rcl_fecPmHistoryDataObject, stl_fecPmHistoryDataObject},
#else
  /* 202 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 203 */ {rcl_layer2DataServicesObject, stl_layer2DataServicesObject},
#else
  /* 203 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 204 */ {rcl_macBridgeServiceProfileObject, stl_macBridgeServiceProfileObject},
#else
  /* 204 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 205 */ {rcl_bCM_MacBridgeServiceProfileObject, stl_bCM_MacBridgeServiceProfileObject},
#else
  /* 205 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 206 */ {rcl_macBridgeConfigDataObject, stl_macBridgeConfigDataObject},
#else
  /* 206 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 207 */ {rcl_macBridgePmHistoryDataObject, stl_macBridgePmHistoryDataObject},
#else
  /* 207 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 208 */ {rcl_macBridgePortConfigDataObject, stl_macBridgePortConfigDataObject},
#else
  /* 208 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 209 */ {rcl_macBridgePortDesignationDataObject, stl_macBridgePortDesignationDataObject},
#else
  /* 209 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 210 */ {rcl_macBridgePortFilterTableDataObject, stl_macBridgePortFilterTableDataObject},
#else
  /* 210 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 211 */ {rcl_macFilterTableObject, stl_macFilterTableObject},
#else
  /* 211 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 212 */ {rcl_macBridgePortFilterPreAssignTableObject, stl_macBridgePortFilterPreAssignTableObject},
#else
  /* 212 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 213 */ {rcl_macBridgePortBridgeTableDataObject, stl_macBridgePortBridgeTableDataObject},
#else
  /* 213 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 214 */ {rcl_bridgeTableObject, stl_bridgeTableObject},
#else
  /* 214 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 215 */ {rcl_macBridgePortPmHistoryDataObject, stl_macBridgePortPmHistoryDataObject},
#else
  /* 215 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 216 */ {rcl_mapperServiceProfileObject, stl_mapperServiceProfileObject},
#else
  /* 216 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 217 */ {rcl_bCM_MapperServiceProfileObject, stl_bCM_MapperServiceProfileObject},
#else
  /* 217 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 218 */ {rcl_vlanTaggingFilterDataObject, stl_vlanTaggingFilterDataObject},
#else
  /* 218 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 219 */ {rcl_vlanTaggingOperationConfigurationDataObject, stl_vlanTaggingOperationConfigurationDataObject},
#else
  /* 219 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 220 */ {rcl_extendedVlanTaggingOperationConfigurationDataObject, stl_extendedVlanTaggingOperationConfigurationDataObject},
#else
  /* 220 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 221 */ {rcl_receivedFrameVlanTaggingOperationTableObject, stl_receivedFrameVlanTaggingOperationTableObject},
#else
  /* 221 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 222 */ {rcl_layer3DataServicesObject, stl_layer3DataServicesObject},
#else
  /* 222 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 223 */ {rcl_ipHostConfigDataObject, stl_ipHostConfigDataObject},
#else
  /* 223 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 224 */ {rcl_bCM_IpHostConfigDataObject, stl_bCM_IpHostConfigDataObject},
#else
  /* 224 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 225 */ {rcl_ipHostPmHistoryDataObject, stl_ipHostPmHistoryDataObject},
#else
  /* 225 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 226 */ {rcl_tcpUdpConfigDataObject, stl_tcpUdpConfigDataObject},
#else
  /* 226 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 227 */ {rcl_ethernetServicesObject, stl_ethernetServicesObject},
#else
  /* 227 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 228 */ {rcl_pptpEthernetUniObject, stl_pptpEthernetUniObject},
#else
  /* 228 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 229 */ {rcl_ethernetPmHistoryDataObject, stl_ethernetPmHistoryDataObject},
#else
  /* 229 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 230 */ {rcl_ethernetPmHistoryData2Object, stl_ethernetPmHistoryData2Object},
#else
  /* 230 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 231 */ {rcl_ethernetPmHistoryData3Object, stl_ethernetPmHistoryData3Object},
#else
  /* 231 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 232 */ {rcl_voiceServicesObject, stl_voiceServicesObject},
#else
  /* 232 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 233 */ {rcl_pptpPotsUniObject, stl_pptpPotsUniObject},
#else
  /* 233 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_SIP_1)
  /* 234 */ {rcl_sipUserDataObject, stl_sipUserDataObject},
#else
  /* 234 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_SIP_1)
  /* 235 */ {rcl_sipAgentConfigDataObject, stl_sipAgentConfigDataObject},
#else
  /* 235 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 236 */ {rcl_voIpVoiceCtpObject, stl_voIpVoiceCtpObject},
#else
  /* 236 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 237 */ {rcl_voIpMediaProfileObject, stl_voIpMediaProfileObject},
#else
  /* 237 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 238 */ {rcl_voiceServiceObject, stl_voiceServiceObject},
#else
  /* 238 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 239 */ {rcl_rtpProfileDataObject, stl_rtpProfileDataObject},
#else
  /* 239 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 240 */ {rcl_voIpAppServiceProfileObject, stl_voIpAppServiceProfileObject},
#else
  /* 240 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 241 */ {rcl_voiceFeatureAccessCodesObject, stl_voiceFeatureAccessCodesObject},
#else
  /* 241 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 242 */ {rcl_networkDialPlanTableObject, stl_networkDialPlanTableObject},
#else
  /* 242 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 243 */ {rcl_dialPlanTableObject, stl_dialPlanTableObject},
#else
  /* 243 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 244 */ {rcl_voIpLineStatusObject, stl_voIpLineStatusObject},
#else
  /* 244 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 245 */ {rcl_callControlPmHistoryDataObject, stl_callControlPmHistoryDataObject},
#else
  /* 245 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 246 */ {rcl_rtpPmHistoryDataObject, stl_rtpPmHistoryDataObject},
#else
  /* 246 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_SIP_1)
  /* 247 */ {rcl_sipAgentPmHistoryDataObject, stl_sipAgentPmHistoryDataObject},
#else
  /* 247 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_SIP_1)
  /* 248 */ {rcl_sipCallInitPmHistoryDataObject, stl_sipCallInitPmHistoryDataObject},
#else
  /* 248 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_MGC_1)
  /* 249 */ {rcl_mgcConfigDataObject, stl_mgcConfigDataObject},
#else
  /* 249 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_MGC_1)
  /* 250 */ {rcl_mgcPmHistoryDataObject, stl_mgcPmHistoryDataObject},
#else
  /* 250 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_VOICE_1) && defined(DMP_X_ITU_ORG_VOICE_1)
  /* 251 */ {rcl_voIpConfigDataObject, stl_voIpConfigDataObject},
#else
  /* 251 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 252 */ {rcl_mocaServicesObject, stl_mocaServicesObject},
#else
  /* 252 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 253 */ {rcl_pptpMocaUniObject, stl_pptpMocaUniObject},
#else
  /* 253 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
  /* 254 */ {rcl_brcmPptpMocaUniObject, stl_brcmPptpMocaUniObject},
#else
  /* 254 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
  /* 255 */ {rcl_mocaStatusObject, stl_mocaStatusObject},
#else
  /* 255 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_BROADCOM_COM_GPON_1)
  /* 256 */ {rcl_mocaStatsObject, stl_mocaStatsObject},
#else
  /* 256 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 257 */ {rcl_mocaEthernetPmHistoryDataObject, stl_mocaEthernetPmHistoryDataObject},
#else
  /* 257 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 258 */ {rcl_mocaInterfacePmHistoryDataObject, stl_mocaInterfacePmHistoryDataObject},
#else
  /* 258 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 259 */ {rcl_mocaInterfacePmHistoryDataNodeTableObject, stl_mocaInterfacePmHistoryDataNodeTableObject},
#else
  /* 259 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 260 */ {rcl_trafficManagementObject, stl_trafficManagementObject},
#else
  /* 260 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 261 */ {rcl_priorityQueueGObject, stl_priorityQueueGObject},
#else
  /* 261 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 262 */ {rcl_trafficSchedulerGObject, stl_trafficSchedulerGObject},
#else
  /* 262 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 263 */ {rcl_gemTrafficDescriptorObject, stl_gemTrafficDescriptorObject},
#else
  /* 263 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 264 */ {rcl_generalObject, stl_generalObject},
#else
  /* 264 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 265 */ {rcl_uniGObject, stl_uniGObject},
#else
  /* 265 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 266 */ {rcl_oltGObject, stl_oltGObject},
#else
  /* 266 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 267 */ {rcl_networkAddressObject, stl_networkAddressObject},
#else
  /* 267 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 268 */ {rcl_authenticationSecurityMethodObject, stl_authenticationSecurityMethodObject},
#else
  /* 268 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 269 */ {rcl_largeStringObject, stl_largeStringObject},
#else
  /* 269 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 270 */ {rcl_thresholdData1Object, stl_thresholdData1Object},
#else
  /* 270 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 271 */ {rcl_thresholdData2Object, stl_thresholdData2Object},
#else
  /* 271 */ {NULL, NULL},
#endif
#if defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1) && defined(DMP_X_ITU_ORG_GPON_1)
  /* 272 */ {rcl_omciObject, stl_omciObject},
#else
  /* 272 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_GPON_1)
  /* 273 */ {rcl_omciSystemObject, stl_omciSystemObject},
#else
  /* 273 */ {NULL, NULL},
#endif
#if defined(DMP_X_BROADCOM_COM_GPON_1)
  /* 274 */ {rcl_gponOmciStatsObject, stl_gponOmciStatsObject},
#else
  /* 274 */ {NULL, NULL},
#endif

};
