/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifndef __RCL_H__
#define __RCL_H__

#include "cms.h"
#include "mdm.h"
#include "cms_core.h"

CmsRet rcl_igdObject( _IGDObject *newObj,
                const _IGDObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_igdDeviceInfoObject( _IGDDeviceInfoObject *newObj,
                const _IGDDeviceInfoObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_vendorConfigFileObject( _VendorConfigFileObject *newObj,
                const _VendorConfigFileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_syslogCfgObject( _SyslogCfgObject *newObj,
                const _SyslogCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_loginCfgObject( _LoginCfgObject *newObj,
                const _LoginCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_appCfgObject( _AppCfgObject *newObj,
                const _AppCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_httpdCfgObject( _HttpdCfgObject *newObj,
                const _HttpdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_tr69cCfgObject( _Tr69cCfgObject *newObj,
                const _Tr69cCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_tr64cCfgObject( _Tr64cCfgObject *newObj,
                const _Tr64cCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sshdCfgObject( _SshdCfgObject *newObj,
                const _SshdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_telnetdCfgObject( _TelnetdCfgObject *newObj,
                const _TelnetdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_consoledCfgObject( _ConsoledCfgObject *newObj,
                const _ConsoledCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_smdCfgObject( _SmdCfgObject *newObj,
                const _SmdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sskCfgObject( _SskCfgObject *newObj,
                const _SskCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_snmpdCfgObject( _SnmpdCfgObject *newObj,
                const _SnmpdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ftpdCfgObject( _FtpdCfgObject *newObj,
                const _FtpdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_tftpdCfgObject( _TftpdCfgObject *newObj,
                const _TftpdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_pppdCfgObject( _PppdCfgObject *newObj,
                const _PppdCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_icmpCfgObject( _IcmpCfgObject *newObj,
                const _IcmpCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_upnpCfgObject( _UpnpCfgObject *newObj,
                const _UpnpCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dnsProxyCfgObject( _DnsProxyCfgObject *newObj,
                const _DnsProxyCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ethernetSwitchObject( _EthernetSwitchObject *newObj,
                const _EthernetSwitchObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_pwrMngtObject( _PwrMngtObject *newObj,
                const _PwrMngtObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_standbyCfgObject( _StandbyCfgObject *newObj,
                const _StandbyCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_deviceConfigObject( _DeviceConfigObject *newObj,
                const _DeviceConfigObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_managementServerObject( _ManagementServerObject *newObj,
                const _ManagementServerObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_manageableDeviceObject( _ManageableDeviceObject *newObj,
                const _ManageableDeviceObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_timeServerCfgObject( _TimeServerCfgObject *newObj,
                const _TimeServerCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2BridgingObject( _L2BridgingObject *newObj,
                const _L2BridgingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2BridgingEntryObject( _L2BridgingEntryObject *newObj,
                const _L2BridgingEntryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2BridgingFilterObject( _L2BridgingFilterObject *newObj,
                const _L2BridgingFilterObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2BridgingIntfObject( _L2BridgingIntfObject *newObj,
                const _L2BridgingIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_qMgmtObject( _QMgmtObject *newObj,
                const _QMgmtObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_qMgmtClassificationObject( _QMgmtClassificationObject *newObj,
                const _QMgmtClassificationObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_qMgmtQueueObject( _QMgmtQueueObject *newObj,
                const _QMgmtQueueObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipPingDiagObject( _IPPingDiagObject *newObj,
                const _IPPingDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanDevObject( _LanDevObject *newObj,
                const _LanDevObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_igmpSnoopingCfgObject( _IgmpSnoopingCfgObject *newObj,
                const _IgmpSnoopingCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanHostCfgObject( _LanHostCfgObject *newObj,
                const _LanHostCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanIpIntfObject( _LanIpIntfObject *newObj,
                const _LanIpIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanIpIntfFirewallExceptionObject( _LanIpIntfFirewallExceptionObject *newObj,
                const _LanIpIntfFirewallExceptionObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipFilterCfgObject( _IpFilterCfgObject *newObj,
                const _IpFilterCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dHCPConditionalServingObject( _DHCPConditionalServingObject *newObj,
                const _DHCPConditionalServingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipv6LanHostCfgObject( _IPv6LanHostCfgObject *newObj,
                const _IPv6LanHostCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mldSnoopingCfgObject( _MldSnoopingCfgObject *newObj,
                const _MldSnoopingCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanEthIntfObject( _LanEthIntfObject *newObj,
                const _LanEthIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanEthIntfStatsObject( _LanEthIntfStatsObject *newObj,
                const _LanEthIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanUsbIntfObject( _LanUsbIntfObject *newObj,
                const _LanUsbIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanUsbIntfStatsObject( _LanUsbIntfStatsObject *newObj,
                const _LanUsbIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanWlanObject( _LanWlanObject *newObj,
                const _LanWlanObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanWlanAssociatedDeviceEntryObject( _LanWlanAssociatedDeviceEntryObject *newObj,
                const _LanWlanAssociatedDeviceEntryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanWlanWepKeyObject( _LanWlanWepKeyObject *newObj,
                const _LanWlanWepKeyObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanWlanPreSharedKeyObject( _LanWlanPreSharedKeyObject *newObj,
                const _LanWlanPreSharedKeyObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlanAdapterObject( _WlanAdapterObject *newObj,
                const _WlanAdapterObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlBaseCfgObject( _WlBaseCfgObject *newObj,
                const _WlBaseCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlStaticWdsCfgObject( _WlStaticWdsCfgObject *newObj,
                const _WlStaticWdsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlWdsCfgObject( _WlWdsCfgObject *newObj,
                const _WlWdsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlScanWdsCfgObject( _WlScanWdsCfgObject *newObj,
                const _WlScanWdsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlMimoCfgObject( _WlMimoCfgObject *newObj,
                const _WlMimoCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlSesCfgObject( _WlSesCfgObject *newObj,
                const _WlSesCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlVirtIntfCfgObject( _WlVirtIntfCfgObject *newObj,
                const _WlVirtIntfCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlMacFltObject( _WlMacFltObject *newObj,
                const _WlMacFltObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlKey64CfgObject( _WlKey64CfgObject *newObj,
                const _WlKey64CfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlKey128CfgObject( _WlKey128CfgObject *newObj,
                const _WlKey128CfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wlWpsCfgObject( _WlWpsCfgObject *newObj,
                const _WlWpsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanMocaIntfObject( _LanMocaIntfObject *newObj,
                const _LanMocaIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanMocaIntfStatusObject( _LanMocaIntfStatusObject *newObj,
                const _LanMocaIntfStatusObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanMocaIntfStatsObject( _LanMocaIntfStatsObject *newObj,
                const _LanMocaIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanHostsObject( _LanHostsObject *newObj,
                const _LanHostsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_lanHostEntryObject( _LanHostEntryObject *newObj,
                const _LanHostEntryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_multiWanObject( _MultiWanObject *newObj,
                const _MultiWanObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mWANPortObject( _MWANPortObject *newObj,
                const _MWANPortObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_failoverCfgObject( _FailoverCfgObject *newObj,
                const _FailoverCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDevObject( _WanDevObject *newObj,
                const _WanDevObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanCommonIntfCfgObject( _WanCommonIntfCfgObject *newObj,
                const _WanCommonIntfCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_xtmInterfaceStatsObject( _XtmInterfaceStatsObject *newObj,
                const _XtmInterfaceStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfCfgObject( _WanDslIntfCfgObject *newObj,
                const _WanDslIntfCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanBertTestObject( _WanBertTestObject *newObj,
                const _WanBertTestObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfStatsObject( _WanDslIntfStatsObject *newObj,
                const _WanDslIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfStatsTotalObject( _WanDslIntfStatsTotalObject *newObj,
                const _WanDslIntfStatsTotalObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfStatsShowtimeObject( _WanDslIntfStatsShowtimeObject *newObj,
                const _WanDslIntfStatsShowtimeObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfStatsCurrentDayObject( _WanDslIntfStatsCurrentDayObject *newObj,
                const _WanDslIntfStatsCurrentDayObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslIntfStatsQuarterHourObject( _WanDslIntfStatsQuarterHourObject *newObj,
                const _WanDslIntfStatsQuarterHourObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslTestParamsObject( _WanDslTestParamsObject *newObj,
                const _WanDslTestParamsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanEthIntfObject( _WanEthIntfObject *newObj,
                const _WanEthIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanEthIntfStatsObject( _WanEthIntfStatsObject *newObj,
                const _WanEthIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanMocaIntfObject( _WanMocaIntfObject *newObj,
                const _WanMocaIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanMocaIntfStatusObject( _WanMocaIntfStatusObject *newObj,
                const _WanMocaIntfStatusObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanMocaIntfStatsObject( _WanMocaIntfStatsObject *newObj,
                const _WanMocaIntfStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2tpAcIntfConfigObject( _L2tpAcIntfConfigObject *newObj,
                const _L2tpAcIntfConfigObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslDiagObject( _WanDslDiagObject *newObj,
                const _WanDslDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslProprietaryDiagObject( _WanDslProprietaryDiagObject *newObj,
                const _WanDslProprietaryDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslDiagPlnObject( _WanDslDiagPlnObject *newObj,
                const _WanDslDiagPlnObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslDiagNonLinearityObject( _WanDslDiagNonLinearityObject *newObj,
                const _WanDslDiagNonLinearityObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanConnDeviceObject( _WanConnDeviceObject *newObj,
                const _WanConnDeviceObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanAtmF4EndToEndLoopbackDiagObject( _WanAtmF4EndToEndLoopbackDiagObject *newObj,
                const _WanAtmF4EndToEndLoopbackDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanAtmF4LoopbackDiagObject( _WanAtmF4LoopbackDiagObject *newObj,
                const _WanAtmF4LoopbackDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanAtmF5EndToEndLoopbackDiagObject( _WanAtmF5EndToEndLoopbackDiagObject *newObj,
                const _WanAtmF5EndToEndLoopbackDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslLinkCfgObject( _WanDslLinkCfgObject *newObj,
                const _WanDslLinkCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDslAtmParamsObject( _WanDslAtmParamsObject *newObj,
                const _WanDslAtmParamsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanAtm5LoopbackDiagObject( _WanAtm5LoopbackDiagObject *newObj,
                const _WanAtm5LoopbackDiagObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPtmLinkCfgObject( _WanPtmLinkCfgObject *newObj,
                const _WanPtmLinkCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanEthLinkCfgObject( _WanEthLinkCfgObject *newObj,
                const _WanEthLinkCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l2tpAcLinkConfigObject( _L2tpAcLinkConfigObject *newObj,
                const _L2tpAcLinkConfigObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanIpConnObject( _WanIpConnObject *newObj,
                const _WanIpConnObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanIpConnPortmappingObject( _WanIpConnPortmappingObject *newObj,
                const _WanIpConnPortmappingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanIpConnPortTriggeringObject( _WanIpConnPortTriggeringObject *newObj,
                const _WanIpConnPortTriggeringObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanIpConnFirewallExceptionObject( _WanIpConnFirewallExceptionObject *newObj,
                const _WanIpConnFirewallExceptionObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macFilterObject( _MacFilterObject *newObj,
                const _MacFilterObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macFilterCfgObject( _MacFilterCfgObject *newObj,
                const _MacFilterCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanIpConnStatsObject( _WanIpConnStatsObject *newObj,
                const _WanIpConnStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPppConnObject( _WanPppConnObject *newObj,
                const _WanPppConnObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPppConnPortmappingObject( _WanPppConnPortmappingObject *newObj,
                const _WanPppConnPortmappingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPppConnPortTriggeringObject( _WanPppConnPortTriggeringObject *newObj,
                const _WanPppConnPortTriggeringObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPppConnFirewallExceptionObject( _WanPppConnFirewallExceptionObject *newObj,
                const _WanPppConnFirewallExceptionObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanPppConnStatsObject( _WanPppConnStatsObject *newObj,
                const _WanPppConnStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l3ForwardingObject( _L3ForwardingObject *newObj,
                const _L3ForwardingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_l3ForwardingEntryObject( _L3ForwardingEntryObject *newObj,
                const _L3ForwardingEntryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipv6L3ForwardingObject( _IPv6L3ForwardingObject *newObj,
                const _IPv6L3ForwardingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipv6L3ForwardingEntryObject( _IPv6L3ForwardingEntryObject *newObj,
                const _IPv6L3ForwardingEntryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_servicesObject( _ServicesObject *newObj,
                const _ServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_remoteAccessObject( _RemoteAccessObject *newObj,
                const _RemoteAccessObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_storageServiceObject( _StorageServiceObject *newObj,
                const _StorageServiceObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_userAccountObject( _UserAccountObject *newObj,
                const _UserAccountObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_capabilitesObject( _CapabilitesObject *newObj,
                const _CapabilitesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_networkInfoObject( _NetworkInfoObject *newObj,
                const _NetworkInfoObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_networkServerObject( _NetworkServerObject *newObj,
                const _NetworkServerObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_physicalMediumObject( _PhysicalMediumObject *newObj,
                const _PhysicalMediumObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_logicalVolumeObject( _LogicalVolumeObject *newObj,
                const _LogicalVolumeObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_folderObject( _FolderObject *newObj,
                const _FolderObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceObject( _VoiceObject *newObj,
                const _VoiceObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceCapObject( _VoiceCapObject *newObj,
                const _VoiceCapObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceCapSipObject( _VoiceCapSipObject *newObj,
                const _VoiceCapSipObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceCapMgcpObject( _VoiceCapMgcpObject *newObj,
                const _VoiceCapMgcpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceCapCodecsObject( _VoiceCapCodecsObject *newObj,
                const _VoiceCapCodecsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfObject( _VoiceProfObject *newObj,
                const _VoiceProfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfProviderObject( _VoiceProfProviderObject *newObj,
                const _VoiceProfProviderObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfSipObject( _VoiceProfSipObject *newObj,
                const _VoiceProfSipObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfSipSubscribeObject( _VoiceProfSipSubscribeObject *newObj,
                const _VoiceProfSipSubscribeObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfMgcpObject( _VoiceProfMgcpObject *newObj,
                const _VoiceProfMgcpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfRtpObject( _VoiceProfRtpObject *newObj,
                const _VoiceProfRtpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfRtpSrtpObject( _VoiceProfRtpSrtpObject *newObj,
                const _VoiceProfRtpSrtpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceProfFaxT38Object( _VoiceProfFaxT38Object *newObj,
                const _VoiceProfFaxT38Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineObject( _VoiceLineObject *newObj,
                const _VoiceLineObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineSipObject( _VoiceLineSipObject *newObj,
                const _VoiceLineSipObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineCallingFeaturesObject( _VoiceLineCallingFeaturesObject *newObj,
                const _VoiceLineCallingFeaturesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineProcessingObject( _VoiceLineProcessingObject *newObj,
                const _VoiceLineProcessingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineCodecObject( _VoiceLineCodecObject *newObj,
                const _VoiceLineCodecObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineCodecListObject( _VoiceLineCodecListObject *newObj,
                const _VoiceLineCodecListObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceLineStatsObject( _VoiceLineStatsObject *newObj,
                const _VoiceLineStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voicePhyIntfObject( _VoicePhyIntfObject *newObj,
                const _VoicePhyIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voicePhyIntfTestsObject( _VoicePhyIntfTestsObject *newObj,
                const _VoicePhyIntfTestsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voicePstnObject( _VoicePstnObject *newObj,
                const _VoicePstnObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceNtrObject( _VoiceNtrObject *newObj,
                const _VoiceNtrObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceNtrHistoryObject( _VoiceNtrHistoryObject *newObj,
                const _VoiceNtrHistoryObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceDECTIntfObject( _VoiceDECTIntfObject *newObj,
                const _VoiceDECTIntfObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceDECTHandsetObject( _VoiceDECTHandsetObject *newObj,
                const _VoiceDECTHandsetObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_snmpCfgObject( _SnmpCfgObject *newObj,
                const _SnmpCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_secDmzHostCfgObject( _SecDmzHostCfgObject *newObj,
                const _SecDmzHostCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macFilterPolicyObject( _MacFilterPolicyObject *newObj,
                const _MacFilterPolicyObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_accessTimeRestrictionObject( _AccessTimeRestrictionObject *newObj,
                const _AccessTimeRestrictionObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_timeScheduleObject( _TimeScheduleObject *newObj,
                const _TimeScheduleObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_urlFilterCfgObject( _UrlFilterCfgObject *newObj,
                const _UrlFilterCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_urlFilterListObject( _UrlFilterListObject *newObj,
                const _UrlFilterListObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dDnsCfgObject( _DDnsCfgObject *newObj,
                const _DDnsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ippCfgObject( _IppCfgObject *newObj,
                const _IppCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dlnaObject( _DlnaObject *newObj,
                const _DlnaObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dmsCfgObject( _DmsCfgObject *newObj,
                const _DmsCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wanDebugPortMirroringCfgObject( _WanDebugPortMirroringCfgObject *newObj,
                const _WanDebugPortMirroringCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipSecCfgObject( _IPSecCfgObject *newObj,
                const _IPSecCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_certificateCfgObject( _CertificateCfgObject *newObj,
                const _CertificateCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wapiCertificateObject( _WapiCertificateObject *newObj,
                const _WapiCertificateObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wapiAsCertificateObject( _WapiAsCertificateObject *newObj,
                const _WapiAsCertificateObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_wapiIssuedCertificateObject( _WapiIssuedCertificateObject *newObj,
                const _WapiIssuedCertificateObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_networkConfigObject( _NetworkConfigObject *newObj,
                const _NetworkConfigObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_interfaceControlObject( _InterfaceControlObject *newObj,
                const _InterfaceControlObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_p8021agCfgObject( _P8021agCfgObject *newObj,
                const _P8021agCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_igmpCfgObject( _IgmpCfgObject *newObj,
                const _IgmpCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mldCfgObject( _MldCfgObject *newObj,
                const _MldCfgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ituTOrgObject( _ItuTOrgObject *newObj,
                const _ItuTOrgObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_g_984_4Object( _G_984_4Object *newObj,
                const _G_984_4Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_equipmentManagementObject( _EquipmentManagementObject *newObj,
                const _EquipmentManagementObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ontGObject( _OntGObject *newObj,
                const _OntGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ont2GObject( _Ont2GObject *newObj,
                const _Ont2GObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ontDataObject( _OntDataObject *newObj,
                const _OntDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_softwareImageObject( _SoftwareImageObject *newObj,
                const _SoftwareImageObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_cardHolderObject( _CardHolderObject *newObj,
                const _CardHolderObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_circuitPackObject( _CircuitPackObject *newObj,
                const _CircuitPackObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_powerSheddingObject( _PowerSheddingObject *newObj,
                const _PowerSheddingObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_portMappingPackageGObject( _PortMappingPackageGObject *newObj,
                const _PortMappingPackageGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_aniManagementObject( _AniManagementObject *newObj,
                const _AniManagementObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_aniGObject( _AniGObject *newObj,
                const _AniGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_tContObject( _TContObject *newObj,
                const _TContObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gemPortNetworkCtpObject( _GemPortNetworkCtpObject *newObj,
                const _GemPortNetworkCtpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_bCM_GemPortNetworkCtpObject( _BCM_GemPortNetworkCtpObject *newObj,
                const _BCM_GemPortNetworkCtpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gemInterworkingTpObject( _GemInterworkingTpObject *newObj,
                const _GemInterworkingTpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_multicastGemInterworkingTpObject( _MulticastGemInterworkingTpObject *newObj,
                const _MulticastGemInterworkingTpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gemInterworkingTpMulticastAddressTableObject( _GemInterworkingTpMulticastAddressTableObject *newObj,
                const _GemInterworkingTpMulticastAddressTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gemPortPmHistoryDataObject( _GemPortPmHistoryDataObject *newObj,
                const _GemPortPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_galEthernetProfileObject( _GalEthernetProfileObject *newObj,
                const _GalEthernetProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_galEthernetPmHistoryDataObject( _GalEthernetPmHistoryDataObject *newObj,
                const _GalEthernetPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_fecPmHistoryDataObject( _FecPmHistoryDataObject *newObj,
                const _FecPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_layer2DataServicesObject( _Layer2DataServicesObject *newObj,
                const _Layer2DataServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgeServiceProfileObject( _MacBridgeServiceProfileObject *newObj,
                const _MacBridgeServiceProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_bCM_MacBridgeServiceProfileObject( _BCM_MacBridgeServiceProfileObject *newObj,
                const _BCM_MacBridgeServiceProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgeConfigDataObject( _MacBridgeConfigDataObject *newObj,
                const _MacBridgeConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePmHistoryDataObject( _MacBridgePmHistoryDataObject *newObj,
                const _MacBridgePmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortConfigDataObject( _MacBridgePortConfigDataObject *newObj,
                const _MacBridgePortConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortDesignationDataObject( _MacBridgePortDesignationDataObject *newObj,
                const _MacBridgePortDesignationDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortFilterTableDataObject( _MacBridgePortFilterTableDataObject *newObj,
                const _MacBridgePortFilterTableDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macFilterTableObject( _MacFilterTableObject *newObj,
                const _MacFilterTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortFilterPreAssignTableObject( _MacBridgePortFilterPreAssignTableObject *newObj,
                const _MacBridgePortFilterPreAssignTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortBridgeTableDataObject( _MacBridgePortBridgeTableDataObject *newObj,
                const _MacBridgePortBridgeTableDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_bridgeTableObject( _BridgeTableObject *newObj,
                const _BridgeTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_macBridgePortPmHistoryDataObject( _MacBridgePortPmHistoryDataObject *newObj,
                const _MacBridgePortPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mapperServiceProfileObject( _MapperServiceProfileObject *newObj,
                const _MapperServiceProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_bCM_MapperServiceProfileObject( _BCM_MapperServiceProfileObject *newObj,
                const _BCM_MapperServiceProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_vlanTaggingFilterDataObject( _VlanTaggingFilterDataObject *newObj,
                const _VlanTaggingFilterDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_vlanTaggingOperationConfigurationDataObject( _VlanTaggingOperationConfigurationDataObject *newObj,
                const _VlanTaggingOperationConfigurationDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_extendedVlanTaggingOperationConfigurationDataObject( _ExtendedVlanTaggingOperationConfigurationDataObject *newObj,
                const _ExtendedVlanTaggingOperationConfigurationDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_receivedFrameVlanTaggingOperationTableObject( _ReceivedFrameVlanTaggingOperationTableObject *newObj,
                const _ReceivedFrameVlanTaggingOperationTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_layer3DataServicesObject( _Layer3DataServicesObject *newObj,
                const _Layer3DataServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipHostConfigDataObject( _IpHostConfigDataObject *newObj,
                const _IpHostConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_bCM_IpHostConfigDataObject( _BCM_IpHostConfigDataObject *newObj,
                const _BCM_IpHostConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ipHostPmHistoryDataObject( _IpHostPmHistoryDataObject *newObj,
                const _IpHostPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_tcpUdpConfigDataObject( _TcpUdpConfigDataObject *newObj,
                const _TcpUdpConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ethernetServicesObject( _EthernetServicesObject *newObj,
                const _EthernetServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_pptpEthernetUniObject( _PptpEthernetUniObject *newObj,
                const _PptpEthernetUniObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ethernetPmHistoryDataObject( _EthernetPmHistoryDataObject *newObj,
                const _EthernetPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ethernetPmHistoryData2Object( _EthernetPmHistoryData2Object *newObj,
                const _EthernetPmHistoryData2Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_ethernetPmHistoryData3Object( _EthernetPmHistoryData3Object *newObj,
                const _EthernetPmHistoryData3Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceServicesObject( _VoiceServicesObject *newObj,
                const _VoiceServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_pptpPotsUniObject( _PptpPotsUniObject *newObj,
                const _PptpPotsUniObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sipUserDataObject( _SipUserDataObject *newObj,
                const _SipUserDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sipAgentConfigDataObject( _SipAgentConfigDataObject *newObj,
                const _SipAgentConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voIpVoiceCtpObject( _VoIpVoiceCtpObject *newObj,
                const _VoIpVoiceCtpObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voIpMediaProfileObject( _VoIpMediaProfileObject *newObj,
                const _VoIpMediaProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceServiceObject( _VoiceServiceObject *newObj,
                const _VoiceServiceObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_rtpProfileDataObject( _RtpProfileDataObject *newObj,
                const _RtpProfileDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voIpAppServiceProfileObject( _VoIpAppServiceProfileObject *newObj,
                const _VoIpAppServiceProfileObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voiceFeatureAccessCodesObject( _VoiceFeatureAccessCodesObject *newObj,
                const _VoiceFeatureAccessCodesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_networkDialPlanTableObject( _NetworkDialPlanTableObject *newObj,
                const _NetworkDialPlanTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_dialPlanTableObject( _DialPlanTableObject *newObj,
                const _DialPlanTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voIpLineStatusObject( _VoIpLineStatusObject *newObj,
                const _VoIpLineStatusObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_callControlPmHistoryDataObject( _CallControlPmHistoryDataObject *newObj,
                const _CallControlPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_rtpPmHistoryDataObject( _RtpPmHistoryDataObject *newObj,
                const _RtpPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sipAgentPmHistoryDataObject( _SipAgentPmHistoryDataObject *newObj,
                const _SipAgentPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_sipCallInitPmHistoryDataObject( _SipCallInitPmHistoryDataObject *newObj,
                const _SipCallInitPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mgcConfigDataObject( _MgcConfigDataObject *newObj,
                const _MgcConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mgcPmHistoryDataObject( _MgcPmHistoryDataObject *newObj,
                const _MgcPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_voIpConfigDataObject( _VoIpConfigDataObject *newObj,
                const _VoIpConfigDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaServicesObject( _MocaServicesObject *newObj,
                const _MocaServicesObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_pptpMocaUniObject( _PptpMocaUniObject *newObj,
                const _PptpMocaUniObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_brcmPptpMocaUniObject( _BrcmPptpMocaUniObject *newObj,
                const _BrcmPptpMocaUniObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaStatusObject( _MocaStatusObject *newObj,
                const _MocaStatusObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaStatsObject( _MocaStatsObject *newObj,
                const _MocaStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaEthernetPmHistoryDataObject( _MocaEthernetPmHistoryDataObject *newObj,
                const _MocaEthernetPmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaInterfacePmHistoryDataObject( _MocaInterfacePmHistoryDataObject *newObj,
                const _MocaInterfacePmHistoryDataObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_mocaInterfacePmHistoryDataNodeTableObject( _MocaInterfacePmHistoryDataNodeTableObject *newObj,
                const _MocaInterfacePmHistoryDataNodeTableObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_trafficManagementObject( _TrafficManagementObject *newObj,
                const _TrafficManagementObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_priorityQueueGObject( _PriorityQueueGObject *newObj,
                const _PriorityQueueGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_trafficSchedulerGObject( _TrafficSchedulerGObject *newObj,
                const _TrafficSchedulerGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gemTrafficDescriptorObject( _GemTrafficDescriptorObject *newObj,
                const _GemTrafficDescriptorObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_generalObject( _GeneralObject *newObj,
                const _GeneralObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_uniGObject( _UniGObject *newObj,
                const _UniGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_oltGObject( _OltGObject *newObj,
                const _OltGObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_networkAddressObject( _NetworkAddressObject *newObj,
                const _NetworkAddressObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_authenticationSecurityMethodObject( _AuthenticationSecurityMethodObject *newObj,
                const _AuthenticationSecurityMethodObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_largeStringObject( _LargeStringObject *newObj,
                const _LargeStringObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_thresholdData1Object( _ThresholdData1Object *newObj,
                const _ThresholdData1Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_thresholdData2Object( _ThresholdData2Object *newObj,
                const _ThresholdData2Object *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_omciObject( _OmciObject *newObj,
                const _OmciObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_omciSystemObject( _OmciSystemObject *newObj,
                const _OmciSystemObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

CmsRet rcl_gponOmciStatsObject( _GponOmciStatsObject *newObj,
                const _GponOmciStatsObject *currObj,
                const InstanceIdStack *iidStack,
                char **errorParam,
                CmsRet *errorCode);

#endif /* __RCL_H__ */
