/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


#ifndef __STL_H__
#define __STL_H__

#include "cms.h"
#include "mdm.h"
#include "cms_core.h"

CmsRet stl_igdObject(_IGDObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_igdDeviceInfoObject(_IGDDeviceInfoObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_vendorConfigFileObject(_VendorConfigFileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_syslogCfgObject(_SyslogCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_loginCfgObject(_LoginCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_appCfgObject(_AppCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_httpdCfgObject(_HttpdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_tr69cCfgObject(_Tr69cCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_tr64cCfgObject(_Tr64cCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sshdCfgObject(_SshdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_telnetdCfgObject(_TelnetdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_consoledCfgObject(_ConsoledCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_smdCfgObject(_SmdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sskCfgObject(_SskCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_snmpdCfgObject(_SnmpdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ftpdCfgObject(_FtpdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_tftpdCfgObject(_TftpdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_pppdCfgObject(_PppdCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_icmpCfgObject(_IcmpCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_upnpCfgObject(_UpnpCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dnsProxyCfgObject(_DnsProxyCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ethernetSwitchObject(_EthernetSwitchObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_pwrMngtObject(_PwrMngtObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_standbyCfgObject(_StandbyCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_deviceConfigObject(_DeviceConfigObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_managementServerObject(_ManagementServerObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_manageableDeviceObject(_ManageableDeviceObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_timeServerCfgObject(_TimeServerCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2BridgingObject(_L2BridgingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2BridgingEntryObject(_L2BridgingEntryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2BridgingFilterObject(_L2BridgingFilterObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2BridgingIntfObject(_L2BridgingIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_qMgmtObject(_QMgmtObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_qMgmtClassificationObject(_QMgmtClassificationObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_qMgmtQueueObject(_QMgmtQueueObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipPingDiagObject(_IPPingDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanDevObject(_LanDevObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_igmpSnoopingCfgObject(_IgmpSnoopingCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanHostCfgObject(_LanHostCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanIpIntfObject(_LanIpIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanIpIntfFirewallExceptionObject(_LanIpIntfFirewallExceptionObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipFilterCfgObject(_IpFilterCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dHCPConditionalServingObject(_DHCPConditionalServingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipv6LanHostCfgObject(_IPv6LanHostCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mldSnoopingCfgObject(_MldSnoopingCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanEthIntfObject(_LanEthIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanEthIntfStatsObject(_LanEthIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanUsbIntfObject(_LanUsbIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanUsbIntfStatsObject(_LanUsbIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanWlanObject(_LanWlanObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanWlanAssociatedDeviceEntryObject(_LanWlanAssociatedDeviceEntryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanWlanWepKeyObject(_LanWlanWepKeyObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanWlanPreSharedKeyObject(_LanWlanPreSharedKeyObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlanAdapterObject(_WlanAdapterObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlBaseCfgObject(_WlBaseCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlStaticWdsCfgObject(_WlStaticWdsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlWdsCfgObject(_WlWdsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlScanWdsCfgObject(_WlScanWdsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlMimoCfgObject(_WlMimoCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlSesCfgObject(_WlSesCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlVirtIntfCfgObject(_WlVirtIntfCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlMacFltObject(_WlMacFltObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlKey64CfgObject(_WlKey64CfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlKey128CfgObject(_WlKey128CfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wlWpsCfgObject(_WlWpsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanMocaIntfObject(_LanMocaIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanMocaIntfStatusObject(_LanMocaIntfStatusObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanMocaIntfStatsObject(_LanMocaIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanHostsObject(_LanHostsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_lanHostEntryObject(_LanHostEntryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_multiWanObject(_MultiWanObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mWANPortObject(_MWANPortObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_failoverCfgObject(_FailoverCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDevObject(_WanDevObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanCommonIntfCfgObject(_WanCommonIntfCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_xtmInterfaceStatsObject(_XtmInterfaceStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfCfgObject(_WanDslIntfCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanBertTestObject(_WanBertTestObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfStatsObject(_WanDslIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfStatsTotalObject(_WanDslIntfStatsTotalObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfStatsShowtimeObject(_WanDslIntfStatsShowtimeObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfStatsCurrentDayObject(_WanDslIntfStatsCurrentDayObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslIntfStatsQuarterHourObject(_WanDslIntfStatsQuarterHourObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslTestParamsObject(_WanDslTestParamsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanEthIntfObject(_WanEthIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanEthIntfStatsObject(_WanEthIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanMocaIntfObject(_WanMocaIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanMocaIntfStatusObject(_WanMocaIntfStatusObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanMocaIntfStatsObject(_WanMocaIntfStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2tpAcIntfConfigObject(_L2tpAcIntfConfigObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslDiagObject(_WanDslDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslProprietaryDiagObject(_WanDslProprietaryDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslDiagPlnObject(_WanDslDiagPlnObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslDiagNonLinearityObject(_WanDslDiagNonLinearityObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanConnDeviceObject(_WanConnDeviceObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanAtmF4EndToEndLoopbackDiagObject(_WanAtmF4EndToEndLoopbackDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanAtmF4LoopbackDiagObject(_WanAtmF4LoopbackDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanAtmF5EndToEndLoopbackDiagObject(_WanAtmF5EndToEndLoopbackDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslLinkCfgObject(_WanDslLinkCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDslAtmParamsObject(_WanDslAtmParamsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanAtm5LoopbackDiagObject(_WanAtm5LoopbackDiagObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPtmLinkCfgObject(_WanPtmLinkCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanEthLinkCfgObject(_WanEthLinkCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l2tpAcLinkConfigObject(_L2tpAcLinkConfigObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanIpConnObject(_WanIpConnObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanIpConnPortmappingObject(_WanIpConnPortmappingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanIpConnPortTriggeringObject(_WanIpConnPortTriggeringObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanIpConnFirewallExceptionObject(_WanIpConnFirewallExceptionObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macFilterObject(_MacFilterObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macFilterCfgObject(_MacFilterCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanIpConnStatsObject(_WanIpConnStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPppConnObject(_WanPppConnObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPppConnPortmappingObject(_WanPppConnPortmappingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPppConnPortTriggeringObject(_WanPppConnPortTriggeringObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPppConnFirewallExceptionObject(_WanPppConnFirewallExceptionObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanPppConnStatsObject(_WanPppConnStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l3ForwardingObject(_L3ForwardingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_l3ForwardingEntryObject(_L3ForwardingEntryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipv6L3ForwardingObject(_IPv6L3ForwardingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipv6L3ForwardingEntryObject(_IPv6L3ForwardingEntryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_servicesObject(_ServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_remoteAccessObject(_RemoteAccessObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_storageServiceObject(_StorageServiceObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_userAccountObject(_UserAccountObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_capabilitesObject(_CapabilitesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_networkInfoObject(_NetworkInfoObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_networkServerObject(_NetworkServerObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_physicalMediumObject(_PhysicalMediumObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_logicalVolumeObject(_LogicalVolumeObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_folderObject(_FolderObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceObject(_VoiceObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceCapObject(_VoiceCapObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceCapSipObject(_VoiceCapSipObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceCapMgcpObject(_VoiceCapMgcpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceCapCodecsObject(_VoiceCapCodecsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfObject(_VoiceProfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfProviderObject(_VoiceProfProviderObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfSipObject(_VoiceProfSipObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfSipSubscribeObject(_VoiceProfSipSubscribeObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfMgcpObject(_VoiceProfMgcpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfRtpObject(_VoiceProfRtpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfRtpSrtpObject(_VoiceProfRtpSrtpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceProfFaxT38Object(_VoiceProfFaxT38Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineObject(_VoiceLineObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineSipObject(_VoiceLineSipObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineCallingFeaturesObject(_VoiceLineCallingFeaturesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineProcessingObject(_VoiceLineProcessingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineCodecObject(_VoiceLineCodecObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineCodecListObject(_VoiceLineCodecListObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceLineStatsObject(_VoiceLineStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voicePhyIntfObject(_VoicePhyIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voicePhyIntfTestsObject(_VoicePhyIntfTestsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voicePstnObject(_VoicePstnObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceNtrObject(_VoiceNtrObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceNtrHistoryObject(_VoiceNtrHistoryObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceDECTIntfObject(_VoiceDECTIntfObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceDECTHandsetObject(_VoiceDECTHandsetObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_snmpCfgObject(_SnmpCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_secDmzHostCfgObject(_SecDmzHostCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macFilterPolicyObject(_MacFilterPolicyObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_accessTimeRestrictionObject(_AccessTimeRestrictionObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_timeScheduleObject(_TimeScheduleObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_urlFilterCfgObject(_UrlFilterCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_urlFilterListObject(_UrlFilterListObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dDnsCfgObject(_DDnsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ippCfgObject(_IppCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dlnaObject(_DlnaObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dmsCfgObject(_DmsCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wanDebugPortMirroringCfgObject(_WanDebugPortMirroringCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipSecCfgObject(_IPSecCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_certificateCfgObject(_CertificateCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wapiCertificateObject(_WapiCertificateObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wapiAsCertificateObject(_WapiAsCertificateObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_wapiIssuedCertificateObject(_WapiIssuedCertificateObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_networkConfigObject(_NetworkConfigObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_interfaceControlObject(_InterfaceControlObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_p8021agCfgObject(_P8021agCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_igmpCfgObject(_IgmpCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mldCfgObject(_MldCfgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ituTOrgObject(_ItuTOrgObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_g_984_4Object(_G_984_4Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_equipmentManagementObject(_EquipmentManagementObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ontGObject(_OntGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ont2GObject(_Ont2GObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ontDataObject(_OntDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_softwareImageObject(_SoftwareImageObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_cardHolderObject(_CardHolderObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_circuitPackObject(_CircuitPackObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_powerSheddingObject(_PowerSheddingObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_portMappingPackageGObject(_PortMappingPackageGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_aniManagementObject(_AniManagementObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_aniGObject(_AniGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_tContObject(_TContObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gemPortNetworkCtpObject(_GemPortNetworkCtpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_bCM_GemPortNetworkCtpObject(_BCM_GemPortNetworkCtpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gemInterworkingTpObject(_GemInterworkingTpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_multicastGemInterworkingTpObject(_MulticastGemInterworkingTpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gemInterworkingTpMulticastAddressTableObject(_GemInterworkingTpMulticastAddressTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gemPortPmHistoryDataObject(_GemPortPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_galEthernetProfileObject(_GalEthernetProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_galEthernetPmHistoryDataObject(_GalEthernetPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_fecPmHistoryDataObject(_FecPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_layer2DataServicesObject(_Layer2DataServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgeServiceProfileObject(_MacBridgeServiceProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_bCM_MacBridgeServiceProfileObject(_BCM_MacBridgeServiceProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgeConfigDataObject(_MacBridgeConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePmHistoryDataObject(_MacBridgePmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortConfigDataObject(_MacBridgePortConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortDesignationDataObject(_MacBridgePortDesignationDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortFilterTableDataObject(_MacBridgePortFilterTableDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macFilterTableObject(_MacFilterTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortFilterPreAssignTableObject(_MacBridgePortFilterPreAssignTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortBridgeTableDataObject(_MacBridgePortBridgeTableDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_bridgeTableObject(_BridgeTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_macBridgePortPmHistoryDataObject(_MacBridgePortPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mapperServiceProfileObject(_MapperServiceProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_bCM_MapperServiceProfileObject(_BCM_MapperServiceProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_vlanTaggingFilterDataObject(_VlanTaggingFilterDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_vlanTaggingOperationConfigurationDataObject(_VlanTaggingOperationConfigurationDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_extendedVlanTaggingOperationConfigurationDataObject(_ExtendedVlanTaggingOperationConfigurationDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_receivedFrameVlanTaggingOperationTableObject(_ReceivedFrameVlanTaggingOperationTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_layer3DataServicesObject(_Layer3DataServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipHostConfigDataObject(_IpHostConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_bCM_IpHostConfigDataObject(_BCM_IpHostConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ipHostPmHistoryDataObject(_IpHostPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_tcpUdpConfigDataObject(_TcpUdpConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ethernetServicesObject(_EthernetServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_pptpEthernetUniObject(_PptpEthernetUniObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ethernetPmHistoryDataObject(_EthernetPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_ethernetPmHistoryData2Object(_EthernetPmHistoryData2Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_ethernetPmHistoryData3Object(_EthernetPmHistoryData3Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceServicesObject(_VoiceServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_pptpPotsUniObject(_PptpPotsUniObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sipUserDataObject(_SipUserDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sipAgentConfigDataObject(_SipAgentConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voIpVoiceCtpObject(_VoIpVoiceCtpObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voIpMediaProfileObject(_VoIpMediaProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceServiceObject(_VoiceServiceObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_rtpProfileDataObject(_RtpProfileDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voIpAppServiceProfileObject(_VoIpAppServiceProfileObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voiceFeatureAccessCodesObject(_VoiceFeatureAccessCodesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_networkDialPlanTableObject(_NetworkDialPlanTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_dialPlanTableObject(_DialPlanTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voIpLineStatusObject(_VoIpLineStatusObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_callControlPmHistoryDataObject(_CallControlPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_rtpPmHistoryDataObject(_RtpPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sipAgentPmHistoryDataObject(_SipAgentPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_sipCallInitPmHistoryDataObject(_SipCallInitPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mgcConfigDataObject(_MgcConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mgcPmHistoryDataObject(_MgcPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_voIpConfigDataObject(_VoIpConfigDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaServicesObject(_MocaServicesObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_pptpMocaUniObject(_PptpMocaUniObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_brcmPptpMocaUniObject(_BrcmPptpMocaUniObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaStatusObject(_MocaStatusObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaStatsObject(_MocaStatsObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaEthernetPmHistoryDataObject(_MocaEthernetPmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaInterfacePmHistoryDataObject(_MocaInterfacePmHistoryDataObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_mocaInterfacePmHistoryDataNodeTableObject(_MocaInterfacePmHistoryDataNodeTableObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_trafficManagementObject(_TrafficManagementObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_priorityQueueGObject(_PriorityQueueGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_trafficSchedulerGObject(_TrafficSchedulerGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gemTrafficDescriptorObject(_GemTrafficDescriptorObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_generalObject(_GeneralObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_uniGObject(_UniGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_oltGObject(_OltGObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_networkAddressObject(_NetworkAddressObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_authenticationSecurityMethodObject(_AuthenticationSecurityMethodObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_largeStringObject(_LargeStringObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_thresholdData1Object(_ThresholdData1Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_thresholdData2Object(_ThresholdData2Object *obj, const InstanceIdStack *iidStack);

CmsRet stl_omciObject(_OmciObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_omciSystemObject(_OmciSystemObject *obj, const InstanceIdStack *iidStack);

CmsRet stl_gponOmciStatsObject(_GponOmciStatsObject *obj, const InstanceIdStack *iidStack);

#endif /* __STL_H__ */
