/*
   <:copyright-gpl
   Copyright 2007 Broadcom Corp. All Rights Reserved.

   This program is free software; you can distribute it and/or modify it
   under the terms of the GNU General Public License (Version 2) as
   published by the Free Software Foundation.

   This program is distributed in the hope it will be useful, but WITHOUT
   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
   for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   59 Temple Place - Suite 330, Boston MA 02111-1307, USA.
   :>
   */

/***************************************************************************
 * File Name  : MoCAcfgdrv.h
 *
 * Description: This file contains the definitions and structures for the
 *              Linux IOCTL interface that used between the user mode
 *              bcmMoCAcfg library and the kernel bcmMoCAcfg driver.
 ***************************************************************************/

#if !defined(_MoCACFGDRV_H_)
#define _MoCACFGDRV_H_

/* Includes. */
#include <bcmmocacfg.h>

/* Defines. */
#define MoCACFGDRV_MAJOR         234
#define MoCACFG_INVALID_FIELD    ((UINT32) -1)

#ifdef MoCA_PQoS_SUPPORT
#define MoCACFGIOCTL_INITIALIZE \
    _IOWR(MoCACFGDRV_MAJOR, 0, MoCACFGDRV_INITIALIZE)
#define MoCACFGIOCTL_UNINITIALIZE \
    _IOR(MoCACFGDRV_MAJOR, 1, MoCACFGDRV_STATUS_ONLY)
#define MoCACFGIOCTL_REINITIALIZE \
    _IOWR(MoCACFGDRV_MAJOR, 2, MoCACFGDRV_REINITIALIZE)
#define MoCACFGIOCTL_GET_INIT_PARMS \
    _IOWR(MoCACFGDRV_MAJOR, 3, MoCACFGDRV_INITIALIZE)
#define MoCACFGIOCTL_GET_CFG \
    _IOWR(MoCACFGDRV_MAJOR, 4, MoCACFGDRV_CONFIG_PARAMS)
#define MoCACFGIOCTL_SET_CFG \
    _IOWR(MoCACFGDRV_MAJOR, 5, MoCACFGDRV_CONFIG_PARAMS)
#define MoCACFGIOCTL_GET_QOS_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 6, MoCACFGDRV_QOS_PARAMS_TABLE)
#define MoCACFGIOCTL_CONFIG_QOS_PARAMS \
    _IOWR(MoCACFGDRV_MAJOR, 7, MoCACFGDRV_QOS_CONFIG_PARAMS)
#define MoCACFGIOCTL_GET_UC_FWD_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 8, MoCACFGDRV_UC_FWD_PARAMS_TABLE)
#define MoCACFGIOCTL_GET_MC_FWD_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 9, MoCACFGDRV_MC_FWD_PARAMS_TABLE)
#define MoCACFGIOCTL_ADD_MC_FWD_TBL_ENTRY \
    _IOWR(MoCACFGDRV_MAJOR, 10, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_DELETE_MC_FWD_TBL_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 11, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_GET_SRC_ADDR_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 12, MoCACFGDRV_SRC_ADDR_PARAMS_TABLE)
#define MoCACFGIOCTL_GET_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 13, MoCACFGDRV_STATUS)
#define MoCACFGIOCTL_GET_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 14, MoCACFGDRV_STATISTICS)
#define MoCACFGIOCTL_GET_NODE_TBL_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 15, MoCACFGDRV_NODE_STATUS_TABLE)
#define MoCACFGIOCTL_GET_NODE_TBL_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 16, MoCACFGDRV_NODE_STATISTICS_TABLE)
#define MoCACFGIOCTL_GET_NODE_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 17, MoCACFGDRV_NODE_STATUS)
#define MoCACFGIOCTL_GET_NODE_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 18, MoCACFGDRV_NODE_STATISTICS)
#define MoCACFGIOCTL_GET_TRACE_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 19, MoCACFGDRV_TRACE_PARAMS)
#define MoCACFGIOCTL_SET_TRACE_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 20, MoCACFGDRV_TRACE_PARAMS)
#define MoCACFGIOCTL_SET_HOST_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 21, MoCACFGDRV_HOST_PARAMS)
#define MoCACFGIOCTL_GET_VERSION \
    _IOWR(MoCACFGDRV_MAJOR, 22, MoCACFGDRV_VERSION)
#define MoCACFGIOCTL_SET_ASNYC_NOTIFY_DESC \
    _IOWR(MoCACFGDRV_MAJOR, 23, MoCACFGDRV_ASYNC_NOTIFY_PARAMS)
#define MoCACFGIOCTL_GET_TRAP_INFO \
    _IOWR(MoCACFGDRV_MAJOR, 24, MoCACFGDRV_ASYNC_INFO)
#define MoCACFGIOCTL_GET_IQ_DATA \
    _IOWR(MoCACFGDRV_MAJOR, 25, MoCACFGDRV_IQ_DATA)
#define MoCACFGIOCTL_GET_SNR_DATA \
    _IOWR(MoCACFGDRV_MAJOR, 26, MoCACFGDRV_SNR_DATA)
#define MoCACFGIOCTL_FUNC_CALL \
    _IOWR(MoCACFGDRV_MAJOR, 27, MoCACFGDRV_FUNC_CALL_PARAMS)
#define MoCACFGIOCTL_CREATE_MC_FWD_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 28, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_DELETE_MC_FWD_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 29, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_FMR_REQUEST \
    _IOWR(MoCACFGDRV_MAJOR, 30, MoCACFGDRV_FMR_REQUEST_PARAMS)
#define MoCACFGIOCTL_CREATE_FLOW \
    _IOWR(MoCACFGDRV_MAJOR, 31, MoCACFGDRV_PQoS_CREATE_PARAMS)
#define MoCACFGIOCTL_INGR_CREATE_REQUEST \
    _IOWR(MoCACFGDRV_MAJOR, 32, MoCACFGDRV_INGR_CREATE_PARAMS)
#define MoCACFGIOCTL_UPDATE_FLOW \
    _IOWR(MoCACFGDRV_MAJOR, 33, MoCACFGDRV_PQoS_CREATE_PARAMS)
#define MoCACFGIOCTL_UPDATE_INGR \
    _IOWR(MoCACFGDRV_MAJOR, 34, MoCACFGDRV_INGR_UPDATE_PARAMS)
#define MoCACFGIOCTL_DELETE_FLOW \
    _IOWR(MoCACFGDRV_MAJOR, 35, MoCACFGDRV_PQoS_DELETE_PARAMS)
#define MoCACFGIOCTL_DELETE_INGR \
    _IOWR(MoCACFGDRV_MAJOR, 36, MoCACFGDRV_INGR_DELETE_PARAMS)
#define MoCACFGIOCTL_LIST_FLOWS \
    _IOWR(MoCACFGDRV_MAJOR, 37, MoCACFGDRV_PQoS_LIST_PARAMS)
#define MoCACFGIOCTL_QUERY_FLOW \
    _IOWR(MoCACFGDRV_MAJOR, 38, MoCACFGDRV_PQoS_QUERY_PARAMS)
#define MoCACFGIOCTL_PQOS_MAINTENANCE \
    _IOWR(MoCACFGDRV_MAJOR, 39, MoCACFGDRV_PQoS_MAINTENANCE_PARAMS)

#define MAX_MoCACFGDRV_IOCTL_COMMANDS   40
#else
#define MoCACFGIOCTL_INITIALIZE \
    _IOWR(MoCACFGDRV_MAJOR, 0, MoCACFGDRV_INITIALIZE)
#define MoCACFGIOCTL_UNINITIALIZE \
    _IOR(MoCACFGDRV_MAJOR, 1, MoCACFGDRV_STATUS_ONLY)
#define MoCACFGIOCTL_REINITIALIZE \
    _IOWR(MoCACFGDRV_MAJOR, 2, MoCACFGDRV_REINITIALIZE)
#define MoCACFGIOCTL_GET_INIT_PARMS \
    _IOWR(MoCACFGDRV_MAJOR, 3, MoCACFGDRV_INITIALIZE)
#define MoCACFGIOCTL_GET_CFG \
    _IOWR(MoCACFGDRV_MAJOR, 4, MoCACFGDRV_CONFIG_PARAMS)
#define MoCACFGIOCTL_SET_CFG \
    _IOWR(MoCACFGDRV_MAJOR, 5, MoCACFGDRV_CONFIG_PARAMS)
#define MoCACFGIOCTL_GET_PQOS_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 6, MoCACFGDRV_PQOS_PARAMS_TABLE)
#define MoCACFGIOCTL_ADD_PQOS_TBL_ENTRY \
    _IOWR(MoCACFGDRV_MAJOR, 7, MoCACFGDRV_PQOS_PARAMS)
#define MoCACFGIOCTL_DELETE_PQOS_TBL_ENTRY \
    _IOWR(MoCACFGDRV_MAJOR, 8, MoCACFGDRV_PQOS_PARAMS)
#define MoCACFGIOCTL_GET_QOS_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 9, MoCACFGDRV_QOS_PARAMS_TABLE)
#define MoCACFGIOCTL_CONFIG_QOS_PARAMS \
    _IOWR(MoCACFGDRV_MAJOR, 10, MoCACFGDRV_QOS_CONFIG_PARAMS)
#define MoCACFGIOCTL_GET_UC_FWD_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 11, MoCACFGDRV_UC_FWD_PARAMS_TABLE)
#define MoCACFGIOCTL_GET_MC_FWD_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 12, MoCACFGDRV_MC_FWD_PARAMS_TABLE)
#define MoCACFGIOCTL_ADD_MC_FWD_TBL_ENTRY \
    _IOWR(MoCACFGDRV_MAJOR, 13, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_DELETE_MC_FWD_TBL_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 14, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_GET_SRC_ADDR_TBL \
    _IOWR(MoCACFGDRV_MAJOR, 15, MoCACFGDRV_SRC_ADDR_PARAMS_TABLE)
#define MoCACFGIOCTL_GET_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 16, MoCACFGDRV_STATUS)
#define MoCACFGIOCTL_GET_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 17, MoCACFGDRV_STATISTICS)
#define MoCACFGIOCTL_GET_NODE_TBL_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 18, MoCACFGDRV_NODE_STATUS_TABLE)
#define MoCACFGIOCTL_GET_NODE_TBL_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 19, MoCACFGDRV_NODE_STATISTICS_TABLE)
#define MoCACFGIOCTL_GET_NODE_STATUS \
    _IOWR(MoCACFGDRV_MAJOR, 20, MoCACFGDRV_NODE_STATUS)
#define MoCACFGIOCTL_GET_NODE_STATISTICS \
    _IOWR(MoCACFGDRV_MAJOR, 21, MoCACFGDRV_NODE_STATISTICS)
#define MoCACFGIOCTL_GET_TRACE_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 22, MoCACFGDRV_TRACE_PARAMS)
#define MoCACFGIOCTL_SET_TRACE_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 23, MoCACFGDRV_TRACE_PARAMS)
#define MoCACFGIOCTL_SET_HOST_CONFIG \
    _IOWR(MoCACFGDRV_MAJOR, 24, MoCACFGDRV_HOST_PARAMS)
#define MoCACFGIOCTL_GET_VERSION \
    _IOWR(MoCACFGDRV_MAJOR, 25, MoCACFGDRV_VERSION)
#define MoCACFGIOCTL_SET_ASNYC_NOTIFY_DESC \
    _IOWR(MoCACFGDRV_MAJOR, 26, MoCACFGDRV_ASYNC_NOTIFY_PARAMS)
#define MoCACFGIOCTL_GET_TRAP_INFO \
    _IOWR(MoCACFGDRV_MAJOR, 27, MoCACFGDRV_ASYNC_INFO)
#define MoCACFGIOCTL_GET_IQ_DATA \
    _IOWR(MoCACFGDRV_MAJOR, 28, MoCACFGDRV_IQ_DATA)
#define MoCACFGIOCTL_GET_SNR_DATA \
    _IOWR(MoCACFGDRV_MAJOR, 29, MoCACFGDRV_SNR_DATA)
#define MoCACFGIOCTL_FUNC_CALL \
    _IOWR(MoCACFGDRV_MAJOR, 30, MoCACFGDRV_FUNC_CALL_PARAMS)
#define MoCACFGIOCTL_CREATE_MC_FWD_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 31, MoCACFGDRV_MC_FWD_ENTRY)
#define MoCACFGIOCTL_DELETE_MC_FWD_GROUP \
    _IOWR(MoCACFGDRV_MAJOR, 32, MoCACFGDRV_MC_FWD_ENTRY)

#define MAX_MoCACFGDRV_IOCTL_COMMANDS   33
#endif

/* Typedefs. */
typedef struct
{
   BCMMoCA_STATUS bmStatus ;
} MoCACFGDRV_STATUS_ONLY, *PMoCACFGDRV_STATUS_ONLY;

typedef struct
{
   MoCA_INITIALIZATION_PARMS Init ;
#ifdef MoCA_INIT_WITH_CONFIG_PARAMS
   MoCA_CONFIG_PARAMS        configParams ;
   UINT32                    configMask ;
#endif
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_INITIALIZE, *PMoCACFGDRV_INITIALIZE;

typedef struct
{
   MoCA_INITIALIZATION_PARMS reInit ;
   UINT32                    reInitMask ;
#ifdef MoCA_INIT_WITH_CONFIG_PARAMS
   MoCA_CONFIG_PARAMS        configParams ;
   UINT32                    configMask ;
#endif
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_REINITIALIZE, *PMoCACFGDRV_REINITIALIZE ;

typedef struct
{
   MoCA_CONFIG_PARAMS        configParams ;
   UINT32                    configMask ;
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_CONFIG_PARAMS, *PMoCACFGDRV_CONFIG_PARAMS ;

typedef struct
{
   PMoCA_PQOS_PARAMS_ENTRY   pMoCAPQosParamsTable ;
   UINT32                    ulPQoSParamsTableSize ;
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_PQOS_PARAMS_TABLE, *PMoCACFGDRV_PQOS_PARAMS_TABLE ;

typedef struct
{
   PMoCA_QOS_PARAMS_ENTRY    pMoCAQoSParamsTable ;
   UINT32                    ulQoSParamsTableSize ;
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_QOS_PARAMS_TABLE, *PMoCACFGDRV_QOS_PARAMS_TABLE ;

typedef struct
{
   MoCA_QOS_PARAMS_ENTRY     QoSConfigParams ;
   BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_QOS_CONFIG_PARAMS, *PMoCACFGDRV_QOS_CONFIG_PARAMS ;

typedef struct
{
   PMoCA_UC_FWD_ENTRY  pMoCAUcFwdParamsTable ;
   UINT32              ulUcFwdTblSize ;
   BCMMoCA_STATUS      bmStatus ;
} MoCACFGDRV_UC_FWD_PARAMS_TABLE, *PMoCACFGDRV_UC_FWD_PARAMS_TABLE ;

typedef struct
{
   MoCA_MC_FWD_ENTRY   MoCAMcFwdEntry ;
   UINT32              ulMcFwdTblSize ;
   BCMMoCA_STATUS      bmStatus ;
} MoCACFGDRV_MC_FWD_ENTRY, *PMoCACFGDRV_MC_FWD_ENTRY ;

typedef struct
{
   PMoCA_MC_FWD_ENTRY  pMoCAMcFwdParamsTable ;
   UINT32              ulMcFwdTblSize ;
   BCMMoCA_STATUS      bmStatus ;
} MoCACFGDRV_MC_FWD_PARAMS_TABLE, *PMoCACFGDRV_MC_FWD_PARAMS_TABLE ;

typedef struct
{
   PMoCA_SRC_ADDR_ENTRY  pMoCASrcAddrParamsTable ;
   UINT32                ulSrcAddrTblSize ;
   BCMMoCA_STATUS        bmStatus ;
} MoCACFGDRV_SRC_ADDR_PARAMS_TABLE, *PMoCACFGDRV_SRC_ADDR_PARAMS_TABLE ;

typedef struct
{
    MoCA_STATUS               MoCAStatus ;
    BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_STATUS, *PMoCACFGDRV_STATUS ;

typedef struct
{
    MoCA_STATISTICS           MoCAStatistics ;
    UINT32                    ulReset ;
    BCMMoCA_STATUS            bmStatus ;
} MoCACFGDRV_STATISTICS, *PMoCACFGDRV_STATISTICS ;

typedef struct
{
    MoCA_NODE_STATUS_ENTRY   MoCANodeStatus ;
    BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_NODE_STATUS, *PMoCACFGDRV_NODE_STATUS ;

typedef struct
{
    MoCA_NODE_STATISTICS_ENTRY   MoCANodeStatistics ;
    UINT32                       ulReset ;
    BCMMoCA_STATUS               bmStatus ;
} MoCACFGDRV_NODE_STATISTICS, *PMoCACFGDRV_NODE_STATISTICS ;

typedef struct
{
    PMoCA_NODE_STATUS_ENTRY         pMoCANodeStatusTable ;
    UINT32                          ulNodeStatusTableSize ;
    MoCA_NODE_COMMON_STATUS_ENTRY   MoCANodeCommonStatus ;
    BCMMoCA_STATUS                  bmStatus ;
} MoCACFGDRV_NODE_STATUS_TABLE, *PMoCACFGDRV_NODE_STATUS_TABLE ;

typedef struct
{
   PMoCA_NODE_STATISTICS_ENTRY        pMoCANodeStatisticsTable ;
   UINT32                             ulReset ;
   UINT32                             ulNodeStatisticsTableSize ;
   BCMMoCA_STATUS                     bmStatus ;
} MoCACFGDRV_NODE_STATISTICS_TABLE, *PMoCACFGDRV_NODE_STATISTICS_TABLE ;

typedef struct
{
   MoCA_TRACE_PARAMS        traceParams ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_TRACE_PARAMS, *PMoCACFGDRV_TRACE_PARAMS ;

typedef struct
{
   MoCA_HOST_PARAMS         hostParams ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_HOST_PARAMS, *PMoCACFGDRV_HOST_PARAMS ;

typedef struct
{
   MoCA_VERSION             version ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_VERSION, *PMoCACFGDRV_VERSION ;

typedef struct
{
   MoCA_ASYNC_NOTIFY_PARAMS asyncNotifyParams ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_ASYNC_NOTIFY_PARAMS, *PMoCACFGDRV_ASYNC_NOTIFY_PARAMS ;

typedef struct
{
   MoCA_ASYNC_INFO          asyncInfo ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_ASYNC_INFO, *PMoCACFGDRV_ASYNC_INFO ;

typedef struct
{
   MoCA_IQ_DATA             iqData ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_IQ_DATA, *PMoCACFGDRV_IQ_DATA ;

typedef struct
{
   MoCA_SNR_DATA            snrData ;
   BCMMoCA_STATUS           bmStatus ;
} MoCACFGDRV_SNR_DATA, *PMoCACFGDRV_SNR_DATA ;

#ifdef MoCA_PQoS_SUPPORT
typedef struct
{
   MoCA_FMR_REQUEST_FULL_PARAMS  fmrData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_FMR_REQUEST_PARAMS, *PMoCACFGDRV_FMR_REQUEST_PARAMS ;

typedef struct
{
   MoCA_PQoS_CREATE_FULL_PARAMS  pqosData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_PQoS_CREATE_PARAMS, *PMoCACFGDRV_PQoS_CREATE_PARAMS ;

typedef struct
{
   MoCA_INGR_CREATE_FULL_PARAMS  ingrData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_INGR_CREATE_PARAMS, *PMoCACFGDRV_INGR_CREATE_PARAMS ;

typedef struct
{
   MoCA_INGR_UPDATE_FULL_PARAMS  ingrData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_INGR_UPDATE_PARAMS, *PMoCACFGDRV_INGR_UPDATE_PARAMS ;

typedef struct
{
   MoCA_PQoS_DELETE_FULL_PARAMS  pqosData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_PQoS_DELETE_PARAMS, *PMoCACFGDRV_PQoS_DELETE_PARAMS ;

typedef struct
{
   MoCA_INGR_DELETE_FULL_PARAMS  ingrData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_INGR_DELETE_PARAMS, *PMoCACFGDRV_INGR_DELETE_PARAMS ;

typedef struct
{
   MoCA_PQoS_LIST_FULL_PARAMS    pqosData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_PQoS_LIST_PARAMS, *PMoCACFGDRV_PQoS_LIST_PARAMS ;

typedef struct
{
   MoCA_PQoS_QUERY_FULL_PARAMS   pqosData ;
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_PQoS_QUERY_PARAMS, *PMoCACFGDRV_PQoS_QUERY_PARAMS ;

typedef struct
{
   BCMMoCA_STATUS                bmStatus ;
} MoCACFGDRV_PQoS_MAINTENANCE_PARAMS, *PMoCACFGDRV_PQoS_MAINTENANCE_PARAMS ;
#endif

typedef struct
{
   MoCA_FUNC_CALL_PARAMS         fnData ;
   BCMMoCA_STATUS                bmStatus ;

} MoCACFGDRV_FUNC_CALL_PARAMS, *PMoCACFGDRV_FUNC_CALL_PARAMS ;

#endif // _MoCACFGDRV_H
